import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProviders from "../components/ClientProviders";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // read cookie server-side to hydrate initial user into client provider
  let initialUser: unknown = undefined;
  try {
    const cookieStore = await cookies();
    const raw = cookieStore.get("scrng_user")?.value;
    if (raw) {
      initialUser = JSON.parse(decodeURIComponent(raw));
    }
  } catch {
    // ignore parse/SSR differences
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProviders initialUser={initialUser}>{children}</ClientProviders>
      </body>
    </html>
  );
}
